# Generated by Django 5.0.6 on 2024-05-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_coffee_amount_alter_coffee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='amount',
            field=models.FloatField(default=None),
        ),
    ]
